/**
 * Markdown renderer for an Investigation.
 *
 * Targets Jira, Confluence and GitHub, so it sticks to widely-supported
 * syntax: headings, tables, fenced code, bold. No HTML, no footnotes, no
 * task lists with custom syntax.
 */

import type { Finding } from '../types/finding';
import type { Investigation, MemoryEvidence, Section } from '../types/investigation';

/** Escape pipe characters so cell content cannot break a table. */
function cell(text: string): string {
  return text.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

/** Render a section that may not have been gathered yet. */
function sectionPlaceholder(section: Section<unknown>, name: string): string | undefined {
  if (section.gathered) return undefined;
  const note = section.note ? `\n\n${section.note}` : '';
  return `### ${name}\n\n**NOT GATHERED** - requires ${section.requires}.${note}\n`;
}

export function renderMarkdown(inv: Investigation): string {
  const out: string[] = [];
  const p = (line = ''): void => {
    out.push(line);
  };

  /* ---- header ---- */
  p(`# Memory Leak Investigation ${inv.id}`);
  p();
  p(inv.title);
  p();
  p(`**Status: ${inv.status}**`);
  p();
  p(
    '> This report is generated by an automated agent. Static findings are ' +
      'hypotheses to investigate, not confirmed leaks. Read the Limitations ' +
      'section before acting on anything here.',
  );
  p();

  /* ---- context ---- */
  p('## 1. Context');
  p();
  p('| | |');
  p('|---|---|');
  p(`| Investigation ID | \`${inv.id}\` |`);
  p(`| Generated | ${inv.createdAt} |`);
  p(`| Project | ${cell(inv.project.packageName ?? '(unnamed)')} |`);
  p(`| Project version | ${cell(inv.project.packageVersion ?? '(unknown)')} |`);
  p(`| Path | \`${cell(inv.project.rootDir)}\` |`);
  p(`| Angular | ${cell(inv.project.angularVersion ?? '(unknown)')} |`);
  p(`| RxJS | ${cell(inv.project.rxjsVersion ?? '(unknown)')} |`);
  p(
    `| Git | ${
      inv.git.isRepository
        ? cell(`${inv.git.branch ?? '?'} @ ${inv.git.shortCommit ?? '?'}`)
        : 'not a repository'
    } |`,
  );
  p(
    `| Working tree | ${
      inv.git.isRepository
        ? inv.git.dirty === true
          ? `**dirty** (${inv.git.uncommittedChanges} change(s))`
          : 'clean'
        : 'n/a'
    } |`,
  );
  p(`| Agent | v${inv.environment.agentVersion} |`);
  p(
    `| Toolchain | Node ${inv.environment.nodeVersion}, TypeScript ${inv.environment.typescriptVersion}, ${inv.environment.platform}/${inv.environment.arch} |`,
  );
  p();

  if (inv.project.supportedCleanupIdioms.length > 0) {
    p('**Cleanup idioms this Angular version supports:**');
    p();
    for (const idiom of inv.project.supportedCleanupIdioms) p(`- \`${idiom}\``);
    p();
    p(
      '_Any proposed fix must use one of these. Suggesting an API the project ' +
        'cannot compile is worse than suggesting nothing._',
    );
    p();
  }

  /* ---- summary ---- */
  p('## 2. Summary');
  p();
  p('| Risk | Count |');
  p('|---|---|');
  p(`| CRITICAL | ${inv.summary.byRisk.CRITICAL} |`);
  p(`| HIGH | ${inv.summary.byRisk.HIGH} |`);
  p(`| MEDIUM | ${inv.summary.byRisk.MEDIUM} |`);
  p(`| LOW | ${inv.summary.byRisk.LOW} |`);
  p();
  p('| Confidence | Count |');
  p('|---|---|');
  p(`| PROVEN | ${inv.summary.byConfidence.PROVEN} |`);
  p(`| LIKELY | ${inv.summary.byConfidence.LIKELY} |`);
  p(`| POSSIBLE | ${inv.summary.byConfidence.POSSIBLE} |`);
  p(`| UNKNOWN | ${inv.summary.byConfidence.UNKNOWN} |`);
  p();
  p(`- Total findings: **${inv.summary.totalFindings}**`);
  if (inv.summary.includedFindings < inv.summary.totalFindings) {
    p(
      `- Reproduced in full below: **${inv.summary.includedFindings}** (highest-scoring). ` +
        `The counts above cover all ${inv.summary.totalFindings}.`,
    );
  }
  p(`- In router-reachable components: **${inv.summary.findingsInRoutedComponents}**`);
  p(`- Strongest evidence held: **${inv.summary.strongestEvidence}**`);
  p();

  if (inv.summary.byConfidence.PROVEN === 0) {
    p(
      '_No finding is PROVEN. Nothing in this report has been observed at ' +
        'runtime - the application was never launched._',
    );
    p();
  }

  /* ---- static findings ---- */
  p('## 3. Static findings');
  p();
  if (inv.staticFindings.length === 0) {
    p('No static findings.');
    p();
  } else {
    p('| # | Risk | Confidence | Finding | Location |');
    p('|---|---|---|---|---|');
    inv.staticFindings.forEach((f, i) => {
      p(
        `| ${i + 1} | ${f.risk} | ${f.confidence} | ${cell(f.title)} | \`${cell(
          `${f.location.file}:${f.location.line}`,
        )}\` |`,
      );
    });
    p();
    p('### Details');
    p();
    inv.staticFindings.forEach((f, i) => renderFindingMarkdown(p, f, i + 1));
  }

  /* ---- runtime sections ---- */
  p('## 4. Runtime investigation');
  p();

  if (inv.scenario.gathered) {
    const s = inv.scenario.data;
    p('### Scenario');
    p();
    p(`**${s.name}** - ${s.description}`);
    p();
    p(`Repeated **${s.iterations}** times. Each iteration:`);
    p();
    s.steps.forEach((step, i) => p(`${i + 1}. ${step}`));
    p();
  } else {
    const placeholder = sectionPlaceholder(inv.scenario, 'Scenario');
    if (placeholder) p(placeholder);
  }

  if (inv.reproductionSteps.gathered) {
    p('### Reproduction steps');
    p();
    p('_Follow these by hand to see the same behaviour without the agent._');
    p();
    for (const step of inv.reproductionSteps.data) p(`- ${step}`);
    p();
  } else {
    const placeholder = sectionPlaceholder(inv.reproductionSteps, 'Reproduction steps');
    if (placeholder) p(placeholder);
  }

  if (inv.runtimeFindings.gathered) {
    const r = inv.runtimeFindings.data;
    p('### Runtime findings');
    p();
    p(`- Chrome ${r.chromeVersion}`);
    p(`- Iterations completed: **${r.iterationsCompleted} / ${r.iterationsRequested}**`);
    p(`- Step failures: **${r.stepFailures.length}**`);
    p();

    if (r.abortedReason !== undefined) {
      p(`> **Run aborted.** ${r.abortedReason}`);
      p();
    }

    if (r.stepFailures.length > 0) {
      p(
        '> **Some steps failed, so the journey performed was not the one written down. ' +
          'Read the memory numbers with that in mind.**',
      );
      p();
      p('| Iteration | Step | Error |');
      p('|---|---|---|');
      for (const f of r.stepFailures.slice(0, 10)) {
        p(`| ${f.iteration} | ${cell(f.description)} | ${cell(f.error)} |`);
      }
      p();
    }

    if (r.console.length > 0) {
      p('**Console errors during the run**');
      p();
      p('| Count | Type | Message |');
      p('|---:|---|---|');
      for (const entry of r.console) {
        const text = entry.text.length > 160 ? entry.text.slice(0, 159) + '…' : entry.text;
        p(`| ${entry.count} | ${entry.type} | ${cell(text)} |`);
      }
      p();
      p(
        '_An error appearing exactly once per iteration is worth attention: it means ' +
          'something fails on every pass of the journey, which often points at state ' +
          'left behind by the previous pass._',
      );
      p();
    } else {
      p('No console errors were recorded.');
      p();
    }
  } else {
    const placeholder = sectionPlaceholder(inv.runtimeFindings, 'Runtime findings');
    if (placeholder) p(placeholder);
  }

  if (inv.memoryEvidence.gathered) {
    renderMemoryMarkdown(p, inv.memoryEvidence.data);
  } else {
    const placeholder = sectionPlaceholder(inv.memoryEvidence, 'Memory evidence');
    if (placeholder) p(placeholder);
  }

  const heapPlaceholder = sectionPlaceholder(inv.heapEvidence, 'Heap and retention evidence');
  if (heapPlaceholder) p(heapPlaceholder);

  p('## 5. Root cause');
  p();
  const rootCausePlaceholder = sectionPlaceholder(inv.rootCause, 'Root cause analysis');
  if (rootCausePlaceholder) p(rootCausePlaceholder);

  p('## 6. Fix');
  p();
  for (const [section, name] of [
    [inv.proposedFixes, 'Proposed fixes'],
    [inv.appliedChanges, 'Applied changes'],
  ] as Array<[Section<unknown>, string]>) {
    const placeholder = sectionPlaceholder(section, name);
    if (placeholder) p(placeholder);
  }

  p('## 7. Verification');
  p();
  for (const [section, name] of [
    [inv.tests, 'Test results'],
    [inv.beforeAfter, 'Before / after comparison'],
    [inv.verification, 'Verification result'],
  ] as Array<[Section<unknown>, string]>) {
    const placeholder = sectionPlaceholder(section, name);
    if (placeholder) p(placeholder);
  }

  /* ---- honesty sections ---- */
  p('## 8. Remaining risks');
  p();
  for (const risk of inv.remainingRisks) p(`- ${risk}`);
  p();

  p('## 9. Limitations');
  p();
  for (const limitation of inv.limitations) p(`- ${limitation}`);
  p();

  p('## 10. Next steps');
  p();
  inv.nextSteps.forEach((step, i) => p(`${i + 1}. ${step}`));
  p();

  p('---');
  p();
  p(
    `_Generated by memory-agent v${inv.environment.agentVersion} at ${inv.createdAt}. ` +
      `Investigation ${inv.id}, status ${inv.status}._`,
  );
  p();

  return out.join('\n');
}

function mb(bytes: number): string {
  return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
}

function signedMb(bytes: number): string {
  const value = bytes / (1024 * 1024);
  return `${value >= 0 ? '+' : ''}${value.toFixed(2)} MB`;
}

function renderMemoryMarkdown(p: (line?: string) => void, m: MemoryEvidence): void {
  p('### Memory evidence');
  p();
  p(`**Verdict: ${m.verdict}**`);
  p();
  p('| | |');
  p('|---|---|');
  p(`| Growth per iteration | **${signedMb(m.bytesPerIteration)}** |`);
  p(`| Total change | ${signedMb(m.totalDeltaBytes)} |`);
  p(`| Line fit (R²) | ${m.rSquared.toFixed(3)} |`);
  p(`| Attached DOM per iteration | ${m.attachedDomPerIteration.toFixed(1)} |`);
  p(`| Listeners per iteration | ${m.listenersPerIteration.toFixed(2)} |`);
  p(`| Samples analysed | ${m.samplesAnalysed} |`);
  p(`| Warm-up discarded | ${m.warmupDiscarded} |`);
  p();
  p(m.interpretation);
  p();

  if (m.caveats.length > 0) {
    p('**Caveats**');
    p();
    for (const caveat of m.caveats) p(`- ${caveat}`);
    p();
  }

  const ungced = m.measurements.filter((x) => x.afterForcedGc === false).length;
  p(
    ungced === 0
      ? '_Every reading was taken after a forced garbage collection, so these are ' +
          'bytes that survived collection rather than uncollected garbage._'
      : `_**${ungced} reading(s) were taken without a forced collection** and may include ` +
          'uncollected garbage. Treat the trend as indicative only._',
  );
  p();

  p('**Readings**');
  p();
  p('| Iteration | Heap | Attached DOM | Listeners |');
  p('|---:|---:|---:|---:|');
  for (const x of m.measurements) {
    p(
      `| ${x.iteration} | ${mb(x.jsHeapUsedBytes ?? 0)} | ${x.attachedDomNodes ?? '-'} | ${x.listeners ?? '-'} |`,
    );
  }
  p();
}

function renderFindingMarkdown(p: (line?: string) => void, f: Finding, rank: number): void {
  p(`#### ${rank}. ${f.title}`);
  p();
  p(`- **Risk:** ${f.risk}  **Confidence:** ${f.confidence}  **Score:** ${f.score}`);
  p(`- **Location:** \`${f.location.file}:${f.location.line}\``);
  p(
    `- **Class:** \`${f.location.className}\`${
      f.location.angularKind ? ` (${f.location.angularKind})` : ''
    } - ${f.hasOnDestroy ? 'has ngOnDestroy' : 'no ngOnDestroy'}`,
  );
  if (f.location.routed && f.location.routePaths) {
    p(`- **Routes:** ${f.location.routePaths.map((r) => `\`${r}\``).join(', ')}`);
  }
  p(`- **Finding ID:** \`${f.id}\``);
  p();

  p('**Why it scored what it did**');
  p();
  p('| Points | Reason |');
  p('|---:|---|');
  for (const factor of f.factors) {
    const sign = factor.points >= 0 ? '+' : '';
    p(`| ${sign}${factor.points} | ${cell(factor.reason)} |`);
  }
  p(`| **${f.score}** | **total** |`);
  p();

  if (f.lifecycleIssues && f.lifecycleIssues.length > 0) {
    p('**Lifecycle defects**');
    p();
    for (const issue of f.lifecycleIssues) {
      const unverified = issue.unverified === true ? ' _(unverified)_' : '';
      p(`- \`${issue.code}\` (${issue.severity})${unverified}: ${issue.message}`);
    }
    p();
  }

  p(`**Why this resource leaks.** ${f.whyItLeaks}`);
  p();
  p(`**How to confirm or refute it.** ${f.recommendedInvestigation}`);
  p();

  if (f.operations.length > 0) {
    p('**Code**');
    p();
    p('```typescript');
    for (const op of f.operations.slice(0, 8)) {
      const hook = op.lifecycleHook ? ` [${op.lifecycleHook}]` : '';
      p(`// line ${op.line}${hook}`);
      p(op.snippet);
    }
    if (f.operations.length > 8) {
      p(`// ... and ${f.operations.length - 8} more`);
    }
    p('```');
    p();
  }
}
