/**
 * Markdown renderer for an Investigation.
 *
 * Targets Jira, Confluence and GitHub, so it sticks to widely-supported
 * syntax: headings, tables, fenced code, bold. No HTML, no footnotes, no
 * task lists with custom syntax.
 */

import type { Finding } from '../types/finding';
import type { Investigation, Section } from '../types/investigation';

/** Escape pipe characters so cell content cannot break a table. */
function cell(text: string): string {
  return text.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

/** Render a section that may not have been gathered yet. */
function sectionPlaceholder(section: Section<unknown>, name: string): string | undefined {
  if (section.gathered) return undefined;
  const note = section.note ? `\n\n${section.note}` : '';
  return `### ${name}\n\n**NOT GATHERED** - requires ${section.requires}.${note}\n`;
}

export function renderMarkdown(inv: Investigation): string {
  const out: string[] = [];
  const p = (line = ''): void => {
    out.push(line);
  };

  /* ---- header ---- */
  p(`# Memory Leak Investigation ${inv.id}`);
  p();
  p(inv.title);
  p();
  p(`**Status: ${inv.status}**`);
  p();
  p(
    '> This report is generated by an automated agent. Static findings are ' +
      'hypotheses to investigate, not confirmed leaks. Read the Limitations ' +
      'section before acting on anything here.',
  );
  p();

  /* ---- context ---- */
  p('## 1. Context');
  p();
  p('| | |');
  p('|---|---|');
  p(`| Investigation ID | \`${inv.id}\` |`);
  p(`| Generated | ${inv.createdAt} |`);
  p(`| Project | ${cell(inv.project.packageName ?? '(unnamed)')} |`);
  p(`| Project version | ${cell(inv.project.packageVersion ?? '(unknown)')} |`);
  p(`| Path | \`${cell(inv.project.rootDir)}\` |`);
  p(`| Angular | ${cell(inv.project.angularVersion ?? '(unknown)')} |`);
  p(`| RxJS | ${cell(inv.project.rxjsVersion ?? '(unknown)')} |`);
  p(
    `| Git | ${
      inv.git.isRepository
        ? cell(`${inv.git.branch ?? '?'} @ ${inv.git.shortCommit ?? '?'}`)
        : 'not a repository'
    } |`,
  );
  p(
    `| Working tree | ${
      inv.git.isRepository
        ? inv.git.dirty === true
          ? `**dirty** (${inv.git.uncommittedChanges} change(s))`
          : 'clean'
        : 'n/a'
    } |`,
  );
  p(`| Agent | v${inv.environment.agentVersion} |`);
  p(
    `| Toolchain | Node ${inv.environment.nodeVersion}, TypeScript ${inv.environment.typescriptVersion}, ${inv.environment.platform}/${inv.environment.arch} |`,
  );
  p();

  if (inv.project.supportedCleanupIdioms.length > 0) {
    p('**Cleanup idioms this Angular version supports:**');
    p();
    for (const idiom of inv.project.supportedCleanupIdioms) p(`- \`${idiom}\``);
    p();
    p(
      '_Any proposed fix must use one of these. Suggesting an API the project ' +
        'cannot compile is worse than suggesting nothing._',
    );
    p();
  }

  /* ---- summary ---- */
  p('## 2. Summary');
  p();
  p('| Risk | Count |');
  p('|---|---|');
  p(`| CRITICAL | ${inv.summary.byRisk.CRITICAL} |`);
  p(`| HIGH | ${inv.summary.byRisk.HIGH} |`);
  p(`| MEDIUM | ${inv.summary.byRisk.MEDIUM} |`);
  p(`| LOW | ${inv.summary.byRisk.LOW} |`);
  p();
  p('| Confidence | Count |');
  p('|---|---|');
  p(`| PROVEN | ${inv.summary.byConfidence.PROVEN} |`);
  p(`| LIKELY | ${inv.summary.byConfidence.LIKELY} |`);
  p(`| POSSIBLE | ${inv.summary.byConfidence.POSSIBLE} |`);
  p(`| UNKNOWN | ${inv.summary.byConfidence.UNKNOWN} |`);
  p();
  p(`- Total findings: **${inv.summary.totalFindings}**`);
  if (inv.summary.includedFindings < inv.summary.totalFindings) {
    p(
      `- Reproduced in full below: **${inv.summary.includedFindings}** (highest-scoring). ` +
        `The counts above cover all ${inv.summary.totalFindings}.`,
    );
  }
  p(`- In router-reachable components: **${inv.summary.findingsInRoutedComponents}**`);
  p(`- Strongest evidence held: **${inv.summary.strongestEvidence}**`);
  p();

  if (inv.summary.byConfidence.PROVEN === 0) {
    p(
      '_No finding is PROVEN. Nothing in this report has been observed at ' +
        'runtime - the application was never launched._',
    );
    p();
  }

  /* ---- static findings ---- */
  p('## 3. Static findings');
  p();
  if (inv.staticFindings.length === 0) {
    p('No static findings.');
    p();
  } else {
    p('| # | Risk | Confidence | Finding | Location |');
    p('|---|---|---|---|---|');
    inv.staticFindings.forEach((f, i) => {
      p(
        `| ${i + 1} | ${f.risk} | ${f.confidence} | ${cell(f.title)} | \`${cell(
          `${f.location.file}:${f.location.line}`,
        )}\` |`,
      );
    });
    p();
    p('### Details');
    p();
    inv.staticFindings.forEach((f, i) => renderFindingMarkdown(p, f, i + 1));
  }

  /* ---- runtime sections ---- */
  p('## 4. Runtime investigation');
  p();
  const runtimeSections: Array<[Section<unknown>, string]> = [
    [inv.scenario, 'Scenario'],
    [inv.reproductionSteps, 'Reproduction steps'],
    [inv.runtimeFindings, 'Runtime findings'],
    [inv.memoryEvidence, 'Memory evidence'],
    [inv.heapEvidence, 'Heap and retention evidence'],
  ];
  for (const [section, name] of runtimeSections) {
    const placeholder = sectionPlaceholder(section, name);
    if (placeholder) p(placeholder);
  }

  p('## 5. Root cause');
  p();
  const rootCausePlaceholder = sectionPlaceholder(inv.rootCause, 'Root cause analysis');
  if (rootCausePlaceholder) p(rootCausePlaceholder);

  p('## 6. Fix');
  p();
  for (const [section, name] of [
    [inv.proposedFixes, 'Proposed fixes'],
    [inv.appliedChanges, 'Applied changes'],
  ] as Array<[Section<unknown>, string]>) {
    const placeholder = sectionPlaceholder(section, name);
    if (placeholder) p(placeholder);
  }

  p('## 7. Verification');
  p();
  for (const [section, name] of [
    [inv.tests, 'Test results'],
    [inv.beforeAfter, 'Before / after comparison'],
    [inv.verification, 'Verification result'],
  ] as Array<[Section<unknown>, string]>) {
    const placeholder = sectionPlaceholder(section, name);
    if (placeholder) p(placeholder);
  }

  /* ---- honesty sections ---- */
  p('## 8. Remaining risks');
  p();
  for (const risk of inv.remainingRisks) p(`- ${risk}`);
  p();

  p('## 9. Limitations');
  p();
  for (const limitation of inv.limitations) p(`- ${limitation}`);
  p();

  p('## 10. Next steps');
  p();
  inv.nextSteps.forEach((step, i) => p(`${i + 1}. ${step}`));
  p();

  p('---');
  p();
  p(
    `_Generated by memory-agent v${inv.environment.agentVersion} at ${inv.createdAt}. ` +
      `Investigation ${inv.id}, status ${inv.status}._`,
  );
  p();

  return out.join('\n');
}

function renderFindingMarkdown(p: (line?: string) => void, f: Finding, rank: number): void {
  p(`#### ${rank}. ${f.title}`);
  p();
  p(`- **Risk:** ${f.risk}  **Confidence:** ${f.confidence}  **Score:** ${f.score}`);
  p(`- **Location:** \`${f.location.file}:${f.location.line}\``);
  p(
    `- **Class:** \`${f.location.className}\`${
      f.location.angularKind ? ` (${f.location.angularKind})` : ''
    } - ${f.hasOnDestroy ? 'has ngOnDestroy' : 'no ngOnDestroy'}`,
  );
  if (f.location.routed && f.location.routePaths) {
    p(`- **Routes:** ${f.location.routePaths.map((r) => `\`${r}\``).join(', ')}`);
  }
  p(`- **Finding ID:** \`${f.id}\``);
  p();

  p('**Why it scored what it did**');
  p();
  p('| Points | Reason |');
  p('|---:|---|');
  for (const factor of f.factors) {
    const sign = factor.points >= 0 ? '+' : '';
    p(`| ${sign}${factor.points} | ${cell(factor.reason)} |`);
  }
  p(`| **${f.score}** | **total** |`);
  p();

  if (f.lifecycleIssues && f.lifecycleIssues.length > 0) {
    p('**Lifecycle defects**');
    p();
    for (const issue of f.lifecycleIssues) {
      const unverified = issue.unverified === true ? ' _(unverified)_' : '';
      p(`- \`${issue.code}\` (${issue.severity})${unverified}: ${issue.message}`);
    }
    p();
  }

  p(`**Why this resource leaks.** ${f.whyItLeaks}`);
  p();
  p(`**How to confirm or refute it.** ${f.recommendedInvestigation}`);
  p();

  if (f.operations.length > 0) {
    p('**Code**');
    p();
    p('```typescript');
    for (const op of f.operations.slice(0, 8)) {
      const hook = op.lifecycleHook ? ` [${op.lifecycleHook}]` : '';
      p(`// line ${op.line}${hook}`);
      p(op.snippet);
    }
    if (f.operations.length > 8) {
      p(`// ... and ${f.operations.length - 8} more`);
    }
    p('```');
    p();
  }
}
